- src/drunc/interface/process_manager.py
- src/drunc/interface/process_manager_shell.py
- src/drunc/process_manager/ssh_process_manager.py
A simple PR which enables graceful shutdown and ensures that session names are provided on boot.
> Process manager

- Dockerfile
- docs/interfacing the process manager.md
- requirements.txt
- src/drunc/interface/process_manager_shell.py
- src/drunc/process_manager/process_manager.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/process_manager/ssh_process_manager.py
Remove some of the redundant interactions.
> PM simplification

- src/drunc/process_manager/ssh_process_manager.py
Pretty much copy-paste from nanorc.
> Add tools to exit if the parent process is interrupted

- src/drunc/process_manager/ssh_process_manager.py
- src/drunc/utils/utils.py
Add log files, doesn't replicate the env variables, and broadcast when something dies.
> SSH pm improvements

- Dockerfile
- data/controller0-conf.json
- data/controller1-conf.json
- data/controller2-conf.json
- data/controller3-conf.json
- data/process-manager-pocket.json
- data/topcontroller-conf.json
- src/drunc/process_manager/boot_json_parser.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/process_manager/ssh_process_manager.py
Explicitly set the work directory and log paths in the boot request. + minor configuration updates.
> Work directories

- data/controller-boot-one.json
- src/drunc/broadcast/server/broadcast_sender.py
- src/drunc/broadcast/server/broadcast_sender_implementation.py
- src/drunc/broadcast/server/kafka_sender.py
- src/drunc/controller/children_interface/child_node.py
- src/drunc/controller/children_interface/grpc_child.py
- src/drunc/controller/children_interface/rest_api_child.py
- src/drunc/controller/controller.py
- src/drunc/controller/interface/controller.py
- src/drunc/process_manager/boot_json_parser.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/process_manager/ssh_process_manager.py
- src/drunc/utils/flask_manager.py
Get to the bottom of this:
- everything was piped to `tee` to get stdout and stderr to logfiles and in RAM. I've removed that, when you send `SIGINT` to a `process |tee file.txt`, the process only gets a `SIGPIPE`, which wasn't enough to close it. Also, all the termination logs get lost due to this (`tee` exits before the process).
- Gunicorn catches all signals (hence it needs to be forked), this is nice and fun, but that means one is responsible for killing the master thread (this is done in the controller terminate method)
Now `log` just reads the log file.
> Controller not stopping

- src/drunc/broadcast/server/broadcast_sender.py
as requested in the ccm meeting today.
> Rename the Kafka topic

- src/drunc/utils/utils.py
Fixes https://github.com/DUNE-DAQ/drunc/issues/46 by catching the `SIGINT` and telling `asyncio` to stop executing the task when it is issued. Revert to normal behaviour between the commands.
> Proper handling of `ctrl-c` during command execution

- src/drunc/process_manager/ssh_process_manager.py
#50 Fixes restart problem in ssh (using develop in druncschema)
> Fixed restarting problem in ssh

- src/drunc/process_manager/configuration.py
- src/drunc/process_manager/ssh_process_manager.py
If the process is alive, the SIG commands are sent, but if they are not, it continues deleting the process from the store. This addresses #60
> Make sure killing also flushes the processes

- src/drunc/controller/controller.py
- src/drunc/controller/stateful_node.py
- src/drunc/fsm/action_factory.py
- src/drunc/fsm/actions/file_logbook.py
- src/drunc/fsm/actions/file_run_registry.py
- src/drunc/fsm/actions/test_action.py
- src/drunc/fsm/actions/user_provided_run_number.py
- src/drunc/fsm/configuration.py
- src/drunc/fsm/core.py
Added `ctx` to all the transition commands, will use this to verify the run number and add the file to the registry if needed.
> Pawel plesniak/fsm file run registry

- src/drunc/process_manager/oks_parser.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/utils/configuration.py
Last night some OKS package names were changed (https://github.com/DUNE-DAQ/daq-release/issues/370); this PR updates the code to account for this
> JCF: update package names to reflect last night's changes

- src/drunc/fsm/exceptions.py
In the fsm exceptions the arguments were removed
> Removing arguments from inside the super()

- src/drunc/process_manager/process_manager.py
- src/drunc/process_manager/ssh_process_manager.py
> Changing boot response from ProcessUUID to ProcessInstance

- src/drunc/utils/utils.py
> The wrong variable was taken as the width, corrected

- src/drunc/fsm/actions/db_run_registry.py
- src/drunc/fsm/actions/file_run_registry.py
Made the changes, tested with test-session
> oksconfgen->daqconf

- src/drunc/controller/children_interface/grpc_child.py
- src/drunc/controller/children_interface/rest_api_child.py
To handle slow applications more gracefully
> Increasing grpc retries and rest timeouts

- src/drunc/broadcast/client/configuration.py
- src/drunc/broadcast/server/broadcast_sender.py
- src/drunc/broadcast/server/configuration.py
- src/drunc/fsm/actions/file_run_registry.py
- src/drunc/utils/configuration.py
Allows for a no broadcast in drunc
> No Broadcast

- src/drunc/process_manager/utils.py
This was not yet asked for, but had started working on it before I realised that we needed it on status rather than ps. Proof of concept for now. 
PIL does not have a hierarchy structure so it seems slightly hacky, if there are better solutions please let me know.
> added a tree structure to ps command

- src/drunc/process_manager/utils.py
> added missing connectivity service from ps tree

- src/drunc/process_manager/utils.py
Reverting back to old flat application name list.
This has all controllers and daq_applications looking flat again and done properly for the next patch release.
It gets the name from the pil and prints it to the ps table
> Flattening PS name structure

- src/drunc/controller/interface/commands.py
- The return type in `filter_sequence_commands` has been corrected, this was returning `None` causing issues down the chain, now it returns an empty `dict`. 
- The return type in `command_desc` failed search for commands is corrected, it now returns the passed arguments rather than dropping them
- Lots of formatting changes added to make transitions more legible.
> Correcting return types, adding formatting

- src/drunc/controller/controller.py
- src/drunc/controller/interface/commands.py
- src/drunc/controller/utils.py
- src/drunc/utils/shell_utils.py
Feature
- If an application goes to error, its controller and the root controller go to error
- No FSM commands will be accepted when in error
> First iteration of error propagation

- src/drunc/broadcast/server/decorators.py
- src/drunc/controller/children_interface/grpc_child.py
- src/drunc/controller/children_interface/rest_api_child.py
- src/drunc/controller/controller.py
A simple PR to print the stacktraces in the logs.
> Stacktrace in logs

- src/drunc/fsm/actions/thread_pinning.py
- src/drunc/fsm/core.py
- src/drunc/process_manager/interface/commands.py
- src/drunc/process_manager/oks_parser.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/unified_shell/commands.py
An attempt at fixing: https://github.com/DUNE-DAQ/confmodel/issues/44
Which along the way would fix: https://github.com/DUNE-DAQ/drunc/issues/203 and would allow the connectivity server port to be set by the user.
> RC env variables

- src/drunc/fsm/actions/thread_pinning.py
- src/drunc/fsm/core.py
- src/drunc/process_manager/interface/commands.py
- src/drunc/process_manager/oks_parser.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/unified_shell/commands.py
> Revert "RC env variables"

- src/drunc/broadcast/client/broadcast_handler.py
- src/drunc/broadcast/server/broadcast_sender.py
- src/drunc/controller/controller.py
- src/drunc/utils/shell_utils.py
Remove the "not implemented" error from logs and shell and transform them to debug messages.
> Remove errors from log and shell

- src/drunc/utils/grpc_utils.py
Addresses Issue # [236](https://github.com/DUNE-DAQ/drunc/issues/236)
> Missing import correction

- src/drunc/controller/interface/shell_utils.py
> Including colors in the execution summary

- src/drunc/controller/children_interface/grpc_child.py
- src/drunc/controller/children_interface/rest_api_child.py
- src/drunc/controller/controller.py
- src/drunc/controller/controller_driver.py
- src/drunc/controller/interface/commands.py
- src/drunc/controller/interface/shell.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/unified_shell/shell.py
- src/drunc/utils/shell_utils.py
Reverts DUNE-DAQ/drunc#239 which broke everything.
> Revert "Recursive statuses"

- src/drunc/process_manager/process_manager_driver.py
> Shuffle boot to make it interruptible

- src/drunc/controller/interface/controller.py
> Don't shut down gracefully if we hangup

- src/drunc/process_manager/oks_parser.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/process_manager/utils.py
The collect_apps() now should generate tree IDs correctly
> Make the tree ID generated recursively

- src/drunc/fsm/actions/db_run_registry.py
Same as https://github.com/DUNE-DAQ/drunc/pull/340 for the patch release
> For patch: Add a jsonified version of the configuration data in the run registry

- src/drunc/fsm/actions/db_run_registry.py
Still needs to be tested with https://github.com/plasorak/offline_conf_reader
> Add a jsonified version of the configuration data in the run registry

- src/drunc/fsm/actions/db_run_registry.py
- src/drunc/fsm/actions/file_run_registry.py
- src/drunc/fsm/actions/thread_pinning.py
- src/drunc/fsm/actions/trigger_rate_specifier.py
- src/drunc/fsm/actions/usvc_elisa_logbook.py
- src/drunc/fsm/actions/usvc_provided_run_number.py
- src/drunc/fsm/actions/utils.py
- src/drunc/fsm/exceptions.py
- src/drunc/tests/fsm/actions/test_utils.py
Fixes https://github.com/DUNE-DAQ/drunc/issues/130
> dotdrunc checks

- setup.cfg
- src/drunc/apps/__main_session_manager__.py
- src/drunc/session_manager/__init__.py
- src/drunc/session_manager/configuration.py
- src/drunc/session_manager/exceptions.py
- src/drunc/session_manager/interface/session_manager.py
- src/drunc/session_manager/session_manager.py
- src/drunc/session_manager/session_manager_driver.py
Resolves ImperialCollegeLondon/drunc#4
Implements a session manager class, and (for now) adds the `describe` and `list_all_sessions` commands.
I just wanted to see if I'm on roughly the right track with this before going too far, hence the draft request. Not ready to merge.
Specifically does what's there look somewhat sensible, abd what is remaining to get this all 'hooked up' to the rest of the drunc code? Cheers.
> Active session (session manager) endpoint

- src/drunc/fsm/actions/db_run_registry.py
- src/drunc/fsm/actions/usvc_elisa_logbook.py
Get the correct flag for prod/test runs
> Run registry fix

- src/drunc/process_manager/ssh_process_manager.py
Same as https://github.com/DUNE-DAQ/drunc/pull/365 for `develop`
> SSH logging

- src/drunc/controller/configuration.py
> Segment confusion

- src/drunc/controller/configuration.py
Same as https://github.com/DUNE-DAQ/drunc/pull/364, but was already fixed so mostly this is an esthetic change. Added a `raise` in front of the exception
> Segment confusion develop

- src/drunc/apps/__main_controller__.py
- src/drunc/apps/__main_controller_shell__.py
- src/drunc/apps/__main_pm__.py
- src/drunc/apps/__main_pm_shell__.py
- src/drunc/apps/__main_session_manager__.py
- src/drunc/apps/__main_unified_shell__.py
- src/drunc/broadcast/server/decorators.py
- src/drunc/controller/controller.py
- src/drunc/controller/interface/controller.py
- src/drunc/controller/interface/shell.py
- src/drunc/process_manager/interface/process_manager.py
- src/drunc/process_manager/interface/shell.py
- src/drunc/process_manager/oks_parser.py
- src/drunc/tests/utils/test_utils.py
- src/drunc/unified_shell/shell.py
- src/drunc/utils/utils.py
Resolves https://github.com/DUNE-DAQ/drunc/issues/369
> Logging fixup

- src/drunc/apps/__main_ssh_validator__.py
- src/drunc/controller/interface/shell_utils.py
Fixes https://github.com/DUNE-DAQ/drunc/issues/373 and the `drunc-ssh-validator`
> Correct typo

- src/drunc/data/process_manager/k8s.json
- src/drunc/data/process_manager/process-manager-k8s-pocket.json
- src/drunc/data/process_manager/ssh-CERN-kafka.json
- src/drunc/data/process_manager/ssh-pocket-kafka.json
- src/drunc/data/process_manager/ssh-standalone.json
- src/drunc/process_manager/configuration.py
- src/drunc/process_manager/interface/process_manager.py
https://github.com/DUNE-DAQ/drunc/issues/351
> Correct fork errors

- src/drunc/apps/__main_ssh_validator__.py
- src/drunc/fsm/actions/thread_pinning.py
Should fix https://github.com/DUNE-DAQ/drunc/issues/399
> Fix wrong config/session

- src/drunc/unified_shell/shell.py
- src/drunc/utils/grpc_utils.py
This PR just removes a long stack trace in case the webproxy is setup at CERN to a simple error message..
> Simpler error

- src/drunc/apps/__main_fake_daqapp_rest__.py
- src/drunc/apps/__main_ssh_validator__.py
- src/drunc/broadcast/client/kafka_stdout_broadcast_handler.py
- src/drunc/broadcast/server/decorators.py
- src/drunc/broadcast/server/grpc_servicer.py
- src/drunc/broadcast/server/kafka_sender.py
- src/drunc/broadcast/utils.py
- src/drunc/controller/children_interface/rest_api_child.py
- src/drunc/controller/controller.py
- src/drunc/controller/interface/context.py
- src/drunc/controller/interface/controller.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/controller/stateful_node.py
- src/drunc/fsm/actions/utils.py
- src/drunc/fsm/core.py
- src/drunc/fsm/exceptions.py
- src/drunc/process_manager/configuration.py
- src/drunc/process_manager/exceptions.py
- src/drunc/process_manager/interface/context.py
- src/drunc/process_manager/k8s_process_manager.py
- src/drunc/process_manager/oks_parser.py
- src/drunc/process_manager/process_manager.py
- src/drunc/process_manager/ssh_process_manager.py
- src/drunc/tests/conftest.py
- src/drunc/tests/utils/test_utils.py
- src/drunc/unified_shell/context.py
- src/drunc/utils/flask_manager.py
- src/drunc/utils/shell_utils.py
- src/drunc/utils/utils.py
Some more ruff linting. Rules have not been added permanently yet.
> First pass of more pedantic ruff.

- src/drunc/session_manager/interface/session_manager.py
Some simple fixes to get the session manager up and running again.
Also fixes session manager logging (oohh, backtraces :eyes: )
Fixes https://github.com/ImperialCollegeLondon/drunc_ui/issues/416
> SessMan: fix server and logging.

- pyproject.toml
- src/drunc/apps/__main_ssh_doctor__.py
This PR adds the `drunc_ssh_doctor` script, an improved version of the ssh validator
> SSH doctor from Alessandro

- src/drunc/data/process_manager/ssh-standalone.json
- src/drunc/process_manager/configuration.py
- src/drunc/process_manager/ssh_process_manager.py
Same as https://github.com/DUNE-DAQ/drunc/pull/434 for the  `patch/v5.3.x` branch
> Thea/no errs with localhost `patch/v5.3.x`

- src/drunc/controller/children_interface/child_node.py
- src/drunc/controller/configuration.py
- src/drunc/controller/controller.py
- src/drunc/controller/interface/commands.py
- src/drunc/controller/interface/controller.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/controller/stateful_node.py
- src/drunc/process_manager/oks_parser.py
- src/drunc/unified_shell/commands.py
This PR makes the following possible.
> Better boots for the patch release

- src/drunc/controller/controller.py
- src/drunc/controller/interface/controller.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/utils/shell_utils.py
This PR changes the visuals of FSM commands in a similar manner to `boot`.
Intended for the patch branch.
Not that in my testing I realised that the FSM error state were not propagating back to the root-controller, so I fixed that too.
> Updating table for FSM commands (patch)

- src/drunc/broadcast/server/decorators.py
- src/drunc/controller/configuration.py
- src/drunc/controller/controller.py
- src/drunc/controller/decorators.py
- src/drunc/controller/stateful_node.py
- src/drunc/data/process_manager/ssh-CERN-kafka.json
- src/drunc/fsm/actions/user_provided_run_number.py
- src/drunc/fsm/actions/usvc_provided_run_number.py
- src/drunc/fsm/actions/utils.py
- src/drunc/fsm/core.py
- src/drunc/process_manager/configuration.py
- src/drunc/process_manager/process_manager.py
The `johnfreeman/wanyunSu/opmon-decorator` branch can be thought of as a recreation of the `wanyunSu/opmon-decorator` branch in the following sense: while `wanyunSu/opmon-decorator` is based on `develop` and consequently contains a lot of code not needed for `patch/fddaq-v5.3.x`, `johnfreeman/wanyunSu/opmon-decorator` was forked off of `patch/fddaq-v5.3.x` and involves my systematically `git cherry-pick`ing Claudia's commits (post-April 16th) from `wanyunSu/opmon-decorator` onto this new feature branch. Where merge conflicts occurred I took pains to ensure the "delta" in the code represented by the cherry-pick was the same as the delta from the original commit. As far as I can tell I only slipped up in this regard once, which I corrected with my own, non-cherry-picked commit, …
> Johnfreeman/wanyun su/opmon decorator

- src/drunc/controller/controller.py
- src/drunc/fsm/core.py
resolved issue #449 
To pass the integration test, one needs to checkout  patch 5.3.x in [druncmessage](https://github.com/DUNE-DAQ/druncmessages/tree/patch/fddaq-v5.3.x/schema/druncschema)
> move run metrics to controller

- src/drunc/controller/controller.py
Requires https://github.com/DUNE-DAQ/druncschema/pull/56
> Use not_executed_not_ready flag for the response

- src/drunc/process_manager/process_manager.py
Addresses https://github.com/DUNE-DAQ/drunc/issues/481
> Logging fix

- src/drunc/fsm/actions/usvc_elisa_logbook.py
Addresses https://github.com/DUNE-DAQ/drunc/issues/486
> Adding the configuration address to the run registry

- src/drunc/process_manager/interface/commands.py
- src/drunc/process_manager/interface/context.py
> fix args order for the PM shell

- .github/ISSUE_TEMPLATE/bug_report.md
Fixing the issue templating
(Indicate issue here: # (issue))
> Adding a second issue template

- .github/ISSUE_TEMPLATE/default_issue_template.md
The SWIT Issue template was not getting recognised. The configuration was missing.
(Indicate issue here: # (issue))
> Integrating the template through the configuration

- src/drunc/process_manager/k8s_process_manager.py
###
This PR refactors the K8sProcessManager to be significantly more robust and reliable. Key improvements include adding proper graceful shutdown for applications, making the kill command synchronous, and improving session stability.
Key Changes
Graceful Shutdown: Applications are now properly terminated, allowing them to shut down cleanly. This is achieved using Kubernetes preStop hooks, which give applications time to save state and close connections before being forced to exit.
Reliable kill Command: The kill process is no longer "fire-and-forget." The manager now waits for confirmation from Kubernetes that a Pod has actually terminated before returning. This prevents race conditions and makes the system's behavior predictable.
Improved Stability: The background process watcher is now …
> K8s PM improvements
