- data/fsm/fsm_configuration.json
- data/fsm/fsm_test_args.json
- src/drunc/fsm/fsm_core.py
- src/drunc/fsm/interfaces/DummyLogbookInterface.py
- src/drunc/tests/__main_fsm__.py
- src/drunc/tests/fake_controller.py
- src/drunc/tests/test_fsm.py
The integ test can now provide arguments to the transitions it executes, getting them from a dict defined in the code. There was also a bug in the fsm_code that meant the transition_data was getting passed a dict as a key, it is now getting passed a string as intended.
> Updated integration tests

- src/drunc/broadcast/client/kafka_stdout_broadcast_handler.py
- src/drunc/process_manager/process_manager.py
- src/drunc/process_manager/ssh_process_manager.py
- src/drunc/utils/utils.py
Add the session (identical to username) in the ssh process manager. Bad but otherwise we'll get Kafka message stumping over each other. Anyway, everybody needs to have their own process manager for ssh.
Add a descriptive groupid for the consumer (timestamped, user-aware and which roughly shows what is consuming).
> Set Kafka groups

- Dockerfile_standalone
With this, one is able to get "patreides" to ssh onto the image and starts the process manager. Still requires `--network host` and having kafka running on 30092.
> Add a standalone docker image

- src/drunc/process_manager/process_manager_driver.py
This is to stop having to modify the configuration all the time and specify the RTE in the session block.
> Use the RTE from the env if not in configuration

- data/process-manager.json
- src/drunc/apps/__main_unified_shell__.py
- src/drunc/process_manager/interface/process_manager.py
- src/drunc/unified_shell/commands.py
- src/drunc/unified_shell/context.py
- src/drunc/unified_shell/shell.py
- src/drunc/utils/utils.py
With this PR, one doesn't need to have 2 terminal windows open simultaneously to start the `drunc-unified-shell`, as the shell directly starts the process manager in a `multiprocess.Process`. To get this to work correctly, there is quite a bit of bookkeeping of the signal that needs to happen (not that on Linux the `multiprocess.Process` are forks):
1. I tied the Process Manager's fate to the drunc-unified-shell's main thread by using the code [here](https://gist.github.com/qxcv/fe5be4d14f855fedf7a5db723aad22c2). This uses magic incantations I don't fully understand, but it works correctly (and is close to a snippet at the top of `nanorc`'s SSHPM), and sends `SIGKILL` to the forked process when the main gets one.
2. When an exception gets thrown in the drunc-unified-shell's main, I …
> Start the ProcessManager in the unified shell

- src/drunc/authoriser/decorators.py
- src/drunc/broadcast/server/decorators.py
- src/drunc/controller/children_interface/grpc_child.py
- src/drunc/controller/children_interface/rest_api_child.py
- src/drunc/controller/controller.py
- src/drunc/controller/decorators.py
- src/drunc/controller/exceptions.py
- src/drunc/controller/interface/commands.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/process_manager/interface/commands.py
- src/drunc/process_manager/process_manager.py
- src/drunc/unified_shell/commands.py
- src/drunc/unified_shell/shell.py
- src/drunc/utils/grpc_utils.py
- src/drunc/utils/shell_utils.py
Changes in this PR:
- Make the schema hierarchical, so the response of a command from a parent contains the responses of all the children
- Implement `ResponseFlag`, a simple Enum which says whether the command was successful or not, it also provides debugging informations
- Do the same as above for the FSM transitions (and standardised the flag name and order between `ResponseFlag` and `FSMResponseFlag`)
- In general, throw less exceptions make the decorator return the correct ResponseFlag when something goes wrong
- ditch the `pack_response` decorator, as it was becoming too complicated.
> Back propagate FSM errors

- src/drunc/apps/__main_controller_shell__.py
- src/drunc/apps/__main_pm_shell__.py
- src/drunc/apps/__main_unified_shell__.py
- src/drunc/broadcast/server/decorators.py
- src/drunc/controller/controller.py
- src/drunc/controller/controller_driver.py
- src/drunc/controller/interface/commands.py
- src/drunc/controller/interface/context.py
- src/drunc/controller/interface/shell.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/exceptions.py
- src/drunc/process_manager/interface/commands.py
- src/drunc/process_manager/interface/context.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/unified_shell/commands.py
- src/drunc/unified_shell/context.py
- src/drunc/unified_shell/shell.py
- src/drunc/utils/shell_utils.py
This PR fixes some of the weirdness in exception handling:
- Assumes that the user always wants a traceback, and remove all the`--traceback` shenanigans.
- Server commands that throw error now return the full traceback as a `Stacktrace` message, or at least it tries to.
- When the server side throws, the client reconstructs an exception (`DruncServerSideError`) from the `Stacktrace`, and, importantly, the message that was originally returned. This means that if one of the child controller throws after a command, the CLI client will still be able to understand what was ran on the other children (albeit not doing anything very interesting right now).
> Exception handling

- src/drunc/utils/utils.py
The `RichHandler` logger defaults to columnwidth=80 when drunc-controller runs in a terminal-less shell.
This PR sets the rich Console column width to 150 (hardcoded value)
> Forcing console width when running w/o terminal

- src/drunc/controller/configuration.py
- src/drunc/fsm/actions/thread_pinning.py
- src/drunc/process_manager/oks_parser.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/process_manager/ssh_process_manager.py
Drunc seemed to boot and configure disabled applications.
The cause was tracked back to 
- `oks_parser.process_segment`: correctly detected disabled apps but did not discard them. A `continue` statement was missing. Added.
- `configuration`: The `ControllerConfHandler.get_children` method defaulted to returning all children, not just the enabled ones. (`get_children` is used by `Controller` to determine what apps to control). Flipped the default to returning only enabled apps. This should be safe for now since `Controller` is the only user
Also renamed `oks_parser.process_*` methods to `oks_parser.collect_*`. `process` seemed too generic and hard to interpret.
> Fixed oks_parser and configurator logic to skip disabled apps

- src/drunc/process_manager/oks_parser.py
Disabled segments were logged as ignored but processed anyway. Added a continue statement after the log message
> Fix disabled segment handling

- setup.cfg
- setup.py
- src/drunc/data/process_manager/k8s.json
- src/drunc/data/process_manager/ssh-CERN-kafka.json
- src/drunc/data/process_manager/ssh-kafka.json
- src/drunc/data/process_manager/ssh-standalone.json
- src/drunc/unified_shell/shell.py
Default process manager configurations have been added to the setuptools drunc package to allow using them w/o having to keep a local drunc copy.
See #103
> Added standard process manager configs to setuptools package

- src/drunc/controller/interface/controller.py
- src/drunc/process_manager/oks_parser.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/process_manager/ssh_process_manager.py
- Added infrastructure application to the list of apps started by process manager (likely to be revisited in the future)
- Added a default EXIT trap to issue an additional SIGTERM to children to applications started with the ssh_process managet to ensure clean termination of processes (gunicorn workers in particular)
> Add support for starting and cleaning terminating infrastructure applications

- src/drunc/controller/interface/commands.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/fsm/exceptions.py
FSM sequences now have their mandatory arguments assigned. 
Transitions, both singular and sequences, print a summary of possible actions color coded in the final line of execution
Appropriate errors constructed and raised where appropriate
> `FSMsequence` adds arguments to corresponding command

- src/drunc/controller/interface/controller.py
- src/drunc/process_manager/ssh_process_manager.py
- No default signal trap
- No trapping of sigterm in controllers
> Rolling back the changes that caused the zombie controller apocalypse

- src/drunc/controller/interface/commands.py
- src/drunc/unified_shell/shell.py
- src/drunc/utils/shell_utils.py
Fixes:
- Line 149 - Correcting missed rich print breaks
- Line 265 - Command name for status summary to use to command name not the whole command
- Lines 13-46 - Not printing a full stack trace when attempting to use a missing configuration
> Cosmetic corrections

- src/drunc/controller/interface/shell_utils.py
The hard coded `rprint` in line 101 prints the options when running `boot`. This is hard coded for now, will be imported from the controller driver in the next release. Issue created - https://github.com/DUNE-DAQ/drunc/issues/148
The corrections in line 164-166 remove the `'NoneType' object has no attribute 'get'` issues observed today.
> No longer attempting to format arguments when none are present

- src/drunc/process_manager/interface/commands.py
- src/drunc/process_manager/interface/shell.py
- src/drunc/process_manager/process_manager.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/process_manager/ssh_process_manager.py
- src/drunc/unified_shell/shell.py
`terminate` existed but was poorly formatted and not actually running. Requires `druncschema` PR#[24](https://github.com/DUNE-DAQ/druncschema/pull/24). Notes
- `terminate` has been implemented as a `process_manager` command. This has been chosen as `controller` does not otherwise have any functions that affect the process.
- Known issue - as this is a `process_manager` command, no current restriction is placed on what `fsm` stage this can be executed from. This is currently the same as `kill --session <session_name>`. This has been raised as an issue, but wanted to include this command for integration tests
- Added `terminate` to `unified-shell`
- With this PR, `terminate` passes around an empty `ProcessQuery`. This does not affect the functionality and will be removed, but as above …
> Fixing `terminate`

- src/drunc/controller/controller.py
- src/drunc/controller/interface/shell_utils.py
The `FSM` model has been reviewed. `terminate` is a `process_manager` command and should not be present in `decribe --command fsm`
> Correcting mislabelled FSM commands

- src/drunc/utils/shell_utils.py
#175 
Caught a key error that craetes a stacktrace when trying to run an FSM command before the session is booted.
Catches KeyError, raises an error that informs user that FSM Commands cannot be sent until the Session is booted and finally stops running completely
> Catch controller commands before boot

- src/drunc/controller/interface/commands.py
- src/drunc/controller/interface/shell.py
- src/drunc/unified_shell/shell.py
I have temporarily defined `wait` as a `controller` command, not a FSM command as per Kurt's request. 
We should discuss the future of the `fsm` prefix before executing FSM commands, as while `wait` is not currently defined as an FSM command, using it in a batch of commands would look like
```
fsm <start_of_batch>
wait
fsm <rest_of_batch>
```
This would also apply to the other commands, so I think this needs to be discussed sooner than later
> Adding wait command

- src/drunc/controller/decorators.py
- src/drunc/controller/exceptions.py
- src/drunc/controller/interface/commands.py
- src/drunc/controller/interface/shell_utils.py
FSM commands can now be sent in batch mode without requiring additional changes - all the commands and arguments get parsed. This still requires work to use all the arguments, but this should be pulled from OKS rather than being hard coded as it is at the moment. 
Features
- can send commands and sequences in batch mode as `fsm <command> <arguments>`. The sequence arguments get duplicated to all of the FSM commands.
- one decorator error resolved.
> Pawel plesniak/batch mode

- src/drunc/controller/children_interface/grpc_child.py
- src/drunc/controller/controller.py
- src/drunc/controller/interface/controller.py
Changes:
- When exiting controllers, no more SIGPIPE
- When terminating a gRPC child, the channel is formally closed, both the channel and controller are deleted, and the broadcast is stopped
- On shutdown the controller now gets SIGKILL not SIGQUIT
- In the controller, on terminate the killed children get removed from the list of children nodes
> Pawel plesniak/terminate no force

- src/drunc/controller/interface/shell.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/process_manager/interface/shell.py
- src/drunc/unified_shell/shell.py
Change the error from a massive stacktrace to a simpler error message when the server side is up, but we cannot connect to it. This is generally caused by having the web proxy on.
> Better error when NP04 proxy is enabled

- src/drunc/process_manager/process_manager_driver.py
This PR aims to make it simpler to debug what is going on when the unified shell cannot find the root controller on the connectivity service by printing a couple of hints. Fixes https://github.com/DUNE-DAQ/drunc/issues/267
> No stack on failed connectivity service lookup

- src/drunc/fsm/actions/thread_pinning.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/process_manager/utils.py
This PR makes drunc work when using `dbt-setup-release` by correctly looking for the RTE script.
> RTE for daq-releases

- src/drunc/fsm/action_factory.py
- src/drunc/fsm/actions/trigger_rate_specifier.py
- src/drunc/fsm/actions/user_provided_run_number.py
- src/drunc/fsm/actions/usvc_provided_run_number.py
With this PR, the default trigger rate at `start` is 0, which I was told would make the application use the default trigger rate from the configuration.
This PR also introduces a `TriggerRateSpecifier` action, that allows the user to change the trigger rate when issuing the `change-rate` command. This last feature must be used in conjunction with the FSM defined in `daqsystemtest`: https://github.com/DUNE-DAQ/daqsystemtest/pull/127.
> Trigger rate change and default

- src/drunc/connectivity_service/client.py
- src/drunc/controller/controller.py
- src/drunc/controller/decorators.py
- src/drunc/utils/utils.py
Attempt to fix https://github.com/DUNE-DAQ/drunc/issues/268
There are 2 problem in that issue:
1. Why is the ControllerActor not the one in charge of the controller?
2. The stack itself which is clearly a bug
For 2., its quite simple.
For 1. this PR made the assumption that the read of the actor happens while the actor is being changed (take_control), therefore leading to this weird, transient error.
> Fix message format and acquire a lock to read the actor token

- src/drunc/utils/shell_utils.py
Simple fix, allows for the correct formatting of the fsm commands when running `status`
> Correcting status format

- src/drunc/process_manager/process_manager_driver.py
Addresses issue [#276](https://github.com/DUNE-DAQ/drunc/issues/276)
Consolidating the db before booting
> Consolidating the db so no faulty configurations get started

- src/drunc/connectivity_service/client.py
- src/drunc/controller/controller.py
- src/drunc/controller/interface/shell.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/process_manager/interface/shell.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/unified_shell/shell.py
- src/drunc/utils/utils.py
This is a PR for a feature branch which perfectly recreates the plasorak/no-stack-on-failed-lookup branch, commit e5d88ede0b752fcada738c6544eee93004d9172a
PR #272 was accidentally merged into `develop` a little while ago. While I've reverted the change to the head of `develop` so that as of this writing it's as if PR #272 hadn't been merged into it, `git`'s conception of the merge history is such that we can't simply re-do the PR with the original feature branch, `plasorak/no-stack-on-failed-lookup`. So what I've done here is create a new feature branch _which is an exact copy of_ `plasorak/no-stack-on-failed-lookup`, enabling a "do-over".
> No stack on failed connectivity service lookup  (redo)

- src/drunc/controller/interface/shell_utils.py
Resolving confusion from PR#[241](https://github.com/DUNE-DAQ/drunc/pull/241)
PR#[71](https://github.com/DUNE-DAQ/drunc/pull/71) was merged, and had the equivalent of one of the commits included, but it was missing this commit
- Mandatory argument structure for `generate_fsm_command` [here](https://github.com/DUNE-DAQ/drunc/pull/241/commits/90e98409c9be43626d3728e02ea827eb5b912e68)
[Other commit](https://github.com/DUNE-DAQ/drunc/pull/241/commits/9b51587d008ccab15e57627f2abf1613ddb815ff) validated to already have been merged with PR#[]().
> Reintroducing changes made in branch plasorak/prettier-cli

- src/drunc/process_manager/interface/commands.py
- src/drunc/process_manager/process_manager.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/process_manager/ssh_process_manager.py
- src/drunc/process_manager/utils.py
Fixes Issue#[185](https://github.com/DUNE-DAQ/drunc/issues/185)
Removes the use of a `ProcessQuery` object from `terminate`
> Pawel plesniak/terminate kill fixes

- src/drunc/data/process_manager/k8s.json
- src/drunc/data/process_manager/ssh-pocket-kafka.json
- src/drunc/data/process_manager/ssh-standalone.json
- src/drunc/process_manager/configuration.py
- src/drunc/process_manager/interface/process_manager.py
- src/drunc/process_manager/process_manager.py
- src/drunc/unified_shell/shell.py
Enable the Process manager to run as a daemon, and the unified shell to connect to it. The target for this is v5.3.0. This fixes https://github.com/DUNE-DAQ/drunc/issues/212
With this PR, the unified shell can be started with
```bash
drunc-unified-shell grpc://some-host:1234 some/oks/config session-name
```
Provided there is a process manager running at `some-host:1234`. That can be done on `some-host` via:
```bash
drunc-process-manager ssh-standalone 1234
```
Alternatively, the process manager's port can be dynamic (0), and in that case the command `drunc-process-manager` will print out which port it is expecting traffic from (and the unified shell can connect to it in the same way).
Of course, the usual command is still valid to start your own process manager:
```bash …
```
> Daemon Process Manager

- src/drunc/controller/children_interface/grpc_child.py
- src/drunc/controller/children_interface/rest_api_child.py
- src/drunc/controller/controller.py
- src/drunc/controller/controller_driver.py
- src/drunc/controller/interface/commands.py
- src/drunc/controller/interface/shell.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/unified_shell/shell.py
- src/drunc/utils/shell_utils.py
All right, let's try to get the recusirve statuses back in. Reverting DUNE-DAQ/drunc#296
> Revert "Revert "Recursive statuses""

- src/drunc/process_manager/configuration.py
This prevents booting `drunc-process-manager`.
> Add missing urlparse import for process manager configuration

- .github/workflows/lint.yml
- .ruff.toml
- setup.py
- src/drunc/broadcast/server/grpc_servicer.py
- src/drunc/controller/children_interface/rest_api_child.py
- src/drunc/fsm/actions/thread_pinning.py
- src/drunc/process_manager/configuration.py
- src/drunc/utils/flask_manager.py
- src/drunc/utils/grpc_utils.py
This PR setups up the repository to use ruff and adds a CI workflow that runs for pull requests.
Currently only one rule is enabled [F821](https://docs.astral.sh/ruff/rules/undefined-name/). This finds undefined names in the code base mostly missing imports but also the odd typo. I've fixed all of the violations that were trivial but there remain a few that need a more expert eye. Plesae feel free to amend this PR with the fixes.
It's worth noting that the full set of [F rules](https://docs.astral.sh/ruff/rules/#pyflakes-f) catches 182 violations but 162 of these can be automatically fixed by ruff. Besides the outstanding F821 violations the remaining things to fix would all be unused imports or unused variables. Both pretty easy to take care of. Worth considering I think to reasonable …
> Add ruff configuration + CI workflow

- src/drunc/controller/interface/shell_utils.py
Addresses https://github.com/DUNE-DAQ/drunc/issues/310
Changes made
- Includes the name of the session in the title in `dark_green`, passed msqt
- Removed redundant import
> Session name is displayed in the top of the status table

- src/drunc/controller/children_interface/rest_api_child.py
- src/drunc/controller/configuration.py
- src/drunc/utils/utils.py
threading children look up, using progress_bar flag for rich.progress
> Wanyun su/threading child look up

- src/drunc/connectivity_service/client.py
While debugging the occasional slow startup of DAQ applications and `drunc` controller applications on Fermilab development computer `daq.fnal.gov`, I noticed that a particular exception type was not being caught in the `publish` function of the `drunc` ConnSvc client code.  This PR has a code change that adds that exception type.
The following steps can be used to demonstrate the behavior of this code change:
```
DATE_PREFIX=`date '+%d%b'`
TIME_SUFFIX=`date '+%H%M'`
source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
setup_dbt latest_v5
dbt-create -n NFD_DEV_241216_A9 ${DATE_PREFIX}FDDevTest_${TIME_SUFFIX}
cd ${DATE_PREFIX}FDDevTest_${TIME_SUFFIX}/sourcecode
git clone https://github.com/DUNE-DAQ/daqsystemtest.git -b develop
cd daqsystemtest; git checkout fc40036a8c; cd ..
cd .. …
```
> Missing exception type in connectivity_service client publish function.

- src/drunc/controller/children_interface/rest_api_child.py
status and the integration test I was running failed. Tracking down the issue was non-trivial, and would have been a lot easier if this message was not a debug, but an error.
> I noticed that when the ping failed, the controller went into error

- src/drunc/process_manager/interface/commands.py
- src/drunc/utils/shell_utils.py
Same as https://github.com/DUNE-DAQ/drunc/pull/331 for the patch branch
> For patch: Delete controller when terminate

- src/drunc/fsm/actions/db_run_registry.py
- src/drunc/fsm/actions/usvc_elisa_logbook.py
Addresses [#328](https://github.com/DUNE-DAQ/drunc/issues/328)
To test
In `ccm.data.xml` from `daqsystemtest`, change `root-controller.fsm` from `fsmConf-test` to `fsmConf-prod`.
Run
```
drunc-unified-shell ssh-standalone config/daqsystemtest/example-configs.data.xml local-2x3-config
boot
conf
start --run-type PROD
drain-dataflow
stop-trigger-sources
stop
start --run-type TEST
drain-dataflow
stop-trigger-sources
stop
start --run-type PROD
drain-dataflow
stop-trigger-sources
stop
start --run-type TEST
drain-dataflow
stop-trigger-sources
stop
terminate
quit
```
Example output
In `logbook.txt`
```
Run 35357 started by pplesnia at 01/24/2025,18:09:19
Current run stopped by pplesnia at 01/24/2025,18:09:29
Run 35358 started by pplesnia at 01/24/2025,18:09:36
Current run stopped by pplesnia at …
```
> Run type issue addressing

- src/drunc/fsm/actions/usvc_elisa_logbook.py
With this PR, one can log to different ELisA that are specified in `~/.drunc.json` and in the `fsm.data.xml`.
> Many ELisAs

- src/drunc/process_manager/ssh_process_manager.py
I was trying to debug why some of my processes were failing to boot, and I was getting a message:
```
[2025/02/27 09:40:02] INFO       ssh_process_manager.py:209     drunc.process_manager.SSH_process_manager:    Process 'hsi-fake-01' (session: 'local-1x1-config', user: 'eflumerf') process exited with exit code 255
```
But there were no log files, and on more investigation, we never `exit(-1)` in our code.
After making this change in ssh_process_manager.py, I get more helpful output:
```
⠋ Looking for root-controller on the connectivity service... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -:--:-- 0:00:00[2025/02/27 09:40:02] INFO       ssh_process_manager.py:209     drunc.process_manager.SSH_process_manager:    Process 'hsi-fake-controller' (session: 'local-1x1-config', user: 'eflumerf') …
```
> Send errors executing the ssh command to the Error log stream (successes are always silent)

- src/drunc/controller/controller.py
- src/drunc/controller/stateful_node.py
- src/drunc/process_manager/process_manager_driver.py
This PR tweaks the imports of some tooling required by `drunc` such that they are imported within the methods/functions that really required them. This is necessary so that `drunc_ui`, which does not need any of that functionality within `drunc`, can import the relevant modules without failure.
The changes made in this PR allow the `drunc_ui` to run, but I don't know if it will cause a problem somewhere else.
> Fix imports of non-standard tooling

- src/drunc/tests/utils/test_utils.py
Handler was not assigned, used old version of `get_logger`
TempFile generates file name as int, corrected to NamedTempFile
Close of filename moved
> corrected log test

- src/drunc/fsm/actions/thread_pinning.py
Add the stdout from the ThreadPinning FSM action to the log files in order to catch errors that do not result in a non-zero exit code (as originally designed in `readout-affinity.py`).
> Verbose output for thread pinning

- .github/workflows/run_pytest.yml
For the testing, the actions install `drunc` and `druncschema` and update the environment. However, when running them from a fork, this process fail since the working branch that this installation is trying to use does not exist in the base repository.
This PR dynamically construct the URL to clone `drunc` and `druncschema` from based on the forked repository owner. When opening a PR directly from the base repository, the URLs will be:
```
https://github.com/DRUNC-DAQ/druncschema.git 
https://github.com/DRUNC-DAQ/drunc.git
```
But when the PR is open from a fork, these become:
```
https://github.com/FORK_OWNER/druncschema.git 
https://github.com/FORK_OWNER/drunc.git
```
Of course, the `druncschema` repo might not exist for that owner, or exist but not a branch with the same name, in which …
> :wrench: Use dynamic repo URL in actions.

- src/drunc/data/process_manager/ssh-standalone.json
- src/drunc/process_manager/configuration.py
- src/drunc/process_manager/ssh_process_manager.py
In computer clusters with shared file system, ssh-ing to localhost can result in ssh host-key mismatch errors.
The cause of this errors is the combination of the ssh `known_hosts` file being located on a shared file system and shared across multiple  servers, but containing the 'localhost' key of the host when `ssh localhost` was executed first.
This little patch tweaks the ssh argument in the ssh process manager to completely bypass host-key checks when the target is localhost.
> Suppress ssh warnings and hostkey errorns when connecting to localhost

- src/drunc/unified_shell/shell.py
- src/drunc/unified_shell/shell_utils.py
- src/drunc/utils/shell_utils.py
This PR adds the following commands to the unified shell:
- `start-run`, which executes the sequence`boot`, `conf`, `start` and `enable-triggers`
- `stop-run` (`disable-triggers`, `drain-dataflow`, `stop-trigger-sources`, `stop`)
- `shutdown` (same as above with the addition of `scrap` and `terminate`.
Implemented in the unified shell _only_, as this requires configuration. Intended for patch release (v5.3.2).
> Sequence commands for patch

- src/drunc/authoriser/decorators.py
- src/drunc/broadcast/server/decorators.py
- src/drunc/controller/decorators.py
- src/drunc/session_manager/session_manager.py
- src/drunc/utils/grpc_utils.py
Simple ish fix after a lot of hunting.
Some of the decorators (e.g. broadcast) silently strip the context var of gRPC commands, which causes problems for commands that don't use the broadcast decorator. Not ideal with layered decorators, but this fix changes it so that the final 'unpack' decorator is the one that strips the context. This should hopefully be a bit more consistent. 
Also fixed session manager's broken logging -- woo! Remote backtraces!
Fixes https://github.com/ImperialCollegeLondon/drunc_ui/issues/417
Fixes https://github.com/ImperialCollegeLondon/drunc_ui/issues/439
> Fix decorators clobbering gRPC context.

- src/drunc/session_manager/session_manager.py
- src/drunc/session_manager/session_manager_driver.py
This PR (finally) implements the searching and returning of actual session configs over the gRPC list_all_configs call.
Configs are searched on `DUNEDAQ_DB_PATH`, so this must be set for this to work. DUNEDAQ_DB_PATH is set in the drunc_ui devel containers already, so this should work out of the box with those. On failure, a FAILURE response is returned for safety.
Currently the files must be named `example-configs.data.xml`, which is obviously less than ideal, but searching for `*.data.xml` failes on, for example, `example-hsi-configs.data.xml` for some reason.
Please reach out if something is not clear.
Resolves https://github.com/ImperialCollegeLondon/drunc/issues/3
> Return real configs in list_all_configs

- src/drunc/controller/children_interface/child_node.py
- src/drunc/controller/children_interface/grpc_child.py
- src/drunc/controller/controller.py
- src/drunc/controller/controller_driver.py
- src/drunc/controller/interface/shell_utils.py
- src/drunc/process_manager/process_manager.py
- src/drunc/process_manager/process_manager_driver.py
- src/drunc/session_manager/session_manager.py
- src/drunc/session_manager/session_manager_driver.py
- src/drunc/tests/controller/test_controller_driver.py
- src/drunc/utils/shell_utils.py
Resolves https://github.com/ImperialCollegeLondon/drunc_ui/issues/496
This is the first in a series of changes which will replace the existing generic gRPC messages (arbitrary data packed to any) to a simpler and more reliable system of purpose-built gRPC messages.
This first PR starts with the Session Manager. Next will come Process Manager and then Controller. There is a sister PR in the druncschema repository required to run this (https://github.com/DUNE-DAQ/druncschema/pull/58).
One can test by running `describe`, `list_all_sessions` and `list_all_configs` on a connected Session Manager driver.
Benefits:
1. type safety is better. We know what a message's type is for free
2. No more `Any`-type packing and unpacking. This is inefficient and hard to follow.
3. We will be able to make …
> SessMan: dedicated gRPC message types

- src/drunc/process_manager/interface/context.py
- src/drunc/process_manager/k8s_process_manager.py
To run this k8s PM
1. SSH into np04-srv-016 and set the k8s configuration:
> export KUBECONFIG=/nfs/home/np04daq/.kube/config.016
2. Set up the DAQ Environment
> cd NFD_DEV_250721_A9 (or latter release.)
> source env.sh
3. Launch the k8s process manager on a chosen port (e.g., 5001)
> drunc-process-manager k8s 5001
You should see output like
>[2025/07/29 15:23:43] INFO       process_manager.py:90          process_manager:                              process_manager communicating through       
address 10.73.136.36:5001       
4.In a new shell, after sourcing the DAQ environment again, connect to the process manager:
>drunc-process-manager-shell grpc://10.73.136.36:5001
where you will be able to send process manager commands like: boot, ps, kill, etc..
5. Boot the applications
>boot …
> k8s process manager

- src/drunc/process_manager/utils.py
Addresses issue #457 
When multiple sessions are booted from non-unified process manager the ps command now sorts by session first, then by process tree hierarchy
Fixes #457 
- [ X] Bug fix (non-breaking change which fixes an issue)
(Indicate issue here: # (issue))
> update tabulate process function to sort by session id too

- src/drunc/utils/shell_utils.py
Addresses issue #505
reduces the ping time of grpc clients from the default of two hours to one minute, which appears to fix the ping_timeout error from #505. Please see the [issue comment](https://github.com/DUNE-DAQ/drunc/issues/505#issuecomment-3214170640) for details and reasoning.
Fixes #505
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] Code is commented, particularly in hard-to-understand areas
(Indicate issue here: # (issue))
> modify connection keepalive setting for grpc clients

- src/drunc/process_manager/interface/commands.py
Addresses issue #543
It looks like commit 0c9a37d reintroduced a bug that was fixed in 1d6ce1b. I'm presuming that the correct behaviour is that the controller is deleted if terminate command is used but not if the kill command is used. With this fixed I'm able to successfully recreate #516 
Fixes #543
- [X ] Bug fix (non-breaking change which fixes an issue)
(Indicate issue here: #543)
> stop kill method in process manager deleting controller

- src/drunc/process_manager/k8s_process_manager.py
!!! Requires https://github.com/DUNE-DAQ/daqsystemtest/pull/244 !!!
Fixes part of https://github.com/DUNE-DAQ/drunc/issues/583.
This PR refactors the Kubernetes networking model. The previous approach, which relied on a manually managed kubectl port-forward subprocess and a socat proxy sidecar, has been replaced with a NodePort service and hostAliases.
Key Changes:
Replaced port-forward with a NodePort Service.
Now: The connection server pod is exposed via a standard Kubernetes NodePort service. This is the idiomatic way to expose a service to external traffic and is managed entirely by the Kubernetes cluster.
Replaced Proxy Sidecar with hostAliases.
Now: The sidecar has been removed. Pods now use the spec.hostAliases field to resolve localhost directly to the ClusterIP of the connection …
> [K8s] Reworking 8s networking, especially for local connectivity service case
